travis:
  secure:
    BINSTAR_TOKEN: owMJEKZZemF94zy+wT1KL4UAX9pDolXx78Jr4HpdJHieeQt4KIynn99mjLcuFQToSsh29rn46u9iOpEZV1u8P0jZCv3PsQG6/1YJg2JwAhcAE/do5zKn8x8jaoUWzZcPlGyKUd6kYTdl644TqzzwszhKnQ2YPAoob2jTNBjrKi3M/qTEFRDsuvBFn/AE40h7K0gO66/Y1yxOsoCwHQq0nCClyVtltB+6avaay3Gwn5RYGnCXCIdyXdSLmGQDCaN7e1P4MUvWNqryI9HOCP82A4UrHP3uvgdfE1thLEOsNUXP0HMfa1ZDV5KfiIg4YjNX+7WBESud52tbgzakdfSOhYOk5O4Tay58SqqnzrC4BdoPNTazamJoxIJxbDFh1/JsN9ihkg4Z4cdzfof54y0DD4MWX1pwj8eTAUe1X7dvLstwP1P23Q3Uz1lrK7dEdIjdrAQ8idlPvhoNnHr3pGbgPn0YEv3Zs30S8WRSPd1aTFp7tZYB7Doc7z7yDwdJJEhvAkpTEqLlo5dFrAxq+CWldt+OVhHBw23gl2E5gtIkmodZaS+GoLxSvnIhynSE0udPT7dJSdvySe09bA3CQjyjyqJ4DAOWupLK/CSR+KamUNztax7egWC7Z0lREpzEVCYKN4TZtItKRrw+E4TWjnXTkrGdn/P9V5sVnzrQirMo6HI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
